version: '3.8'

services:
  client:
    image: dannyazzawi/tic-tac-go:client-1.0.0
    ports:
      - "8080:8080"
    networks:
      - my_network

  server:
    image: dannyazzawi/tic-tac-go:server-1.0.0
    ports:
      - "8081:8081"
    environment:
      - LISTENING_PORT=8081
      - DATABASE_HOST=redis:6379
      - DATABASE_PASSWORD=
    networks:
      - my_network

  redis:
    image: redis/redis-stack-server:7.2.0-v8
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
